name: freemium_hub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.2
  extended_image: ^6.2.1
  file_picker: ^5.2.4
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_native_api: ^0.0.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_wallpaper_manager: ^0.0.3
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_cropper: ^3.0.1
  image_downloader: ^0.31.0
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  permission_handler: ^9.0.1
  photo_view: ^0.14.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
